// Package pkg1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package pkg1

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/go-chi/chi/v5"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// TestHeaderFixedNoContent request
	TestHeaderFixedNoContent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TestHeaderNoContent request
	TestHeaderNoContent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TestRefHeaderFixedNoContent request
	TestRefHeaderFixedNoContent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TestRefHeaderNoContent request
	TestRefHeaderNoContent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) TestHeaderFixedNoContent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTestHeaderFixedNoContentRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TestHeaderNoContent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTestHeaderNoContentRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TestRefHeaderFixedNoContent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTestRefHeaderFixedNoContentRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TestRefHeaderNoContent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTestRefHeaderNoContentRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewTestHeaderFixedNoContentRequest generates requests for TestHeaderFixedNoContent
func NewTestHeaderFixedNoContentRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/test-header-fixed-nocontent")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTestHeaderNoContentRequest generates requests for TestHeaderNoContent
func NewTestHeaderNoContentRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/test-header-nocontent")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTestRefHeaderFixedNoContentRequest generates requests for TestRefHeaderFixedNoContent
func NewTestRefHeaderFixedNoContentRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/test-ref-header-fixed-nocontent")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTestRefHeaderNoContentRequest generates requests for TestRefHeaderNoContent
func NewTestRefHeaderNoContentRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/test-ref-header-nocontent")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// TestHeaderFixedNoContentWithResponse request
	TestHeaderFixedNoContentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestHeaderFixedNoContentResponse, error)

	// TestHeaderNoContentWithResponse request
	TestHeaderNoContentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestHeaderNoContentResponse, error)

	// TestRefHeaderFixedNoContentWithResponse request
	TestRefHeaderFixedNoContentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestRefHeaderFixedNoContentResponse, error)

	// TestRefHeaderNoContentWithResponse request
	TestRefHeaderNoContentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestRefHeaderNoContentResponse, error)
}

type TestHeaderFixedNoContentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r TestHeaderFixedNoContentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TestHeaderFixedNoContentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TestHeaderNoContentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r TestHeaderNoContentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TestHeaderNoContentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TestRefHeaderFixedNoContentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r TestRefHeaderFixedNoContentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TestRefHeaderFixedNoContentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TestRefHeaderNoContentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r TestRefHeaderNoContentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TestRefHeaderNoContentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// TestHeaderFixedNoContentWithResponse request returning *TestHeaderFixedNoContentResponse
func (c *ClientWithResponses) TestHeaderFixedNoContentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestHeaderFixedNoContentResponse, error) {
	rsp, err := c.TestHeaderFixedNoContent(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTestHeaderFixedNoContentResponse(rsp)
}

// TestHeaderNoContentWithResponse request returning *TestHeaderNoContentResponse
func (c *ClientWithResponses) TestHeaderNoContentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestHeaderNoContentResponse, error) {
	rsp, err := c.TestHeaderNoContent(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTestHeaderNoContentResponse(rsp)
}

// TestRefHeaderFixedNoContentWithResponse request returning *TestRefHeaderFixedNoContentResponse
func (c *ClientWithResponses) TestRefHeaderFixedNoContentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestRefHeaderFixedNoContentResponse, error) {
	rsp, err := c.TestRefHeaderFixedNoContent(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTestRefHeaderFixedNoContentResponse(rsp)
}

// TestRefHeaderNoContentWithResponse request returning *TestRefHeaderNoContentResponse
func (c *ClientWithResponses) TestRefHeaderNoContentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestRefHeaderNoContentResponse, error) {
	rsp, err := c.TestRefHeaderNoContent(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTestRefHeaderNoContentResponse(rsp)
}

// ParseTestHeaderFixedNoContentResponse parses an HTTP response from a TestHeaderFixedNoContentWithResponse call
func ParseTestHeaderFixedNoContentResponse(rsp *http.Response) (*TestHeaderFixedNoContentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TestHeaderFixedNoContentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseTestHeaderNoContentResponse parses an HTTP response from a TestHeaderNoContentWithResponse call
func ParseTestHeaderNoContentResponse(rsp *http.Response) (*TestHeaderNoContentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TestHeaderNoContentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseTestRefHeaderFixedNoContentResponse parses an HTTP response from a TestRefHeaderFixedNoContentWithResponse call
func ParseTestRefHeaderFixedNoContentResponse(rsp *http.Response) (*TestRefHeaderFixedNoContentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TestRefHeaderFixedNoContentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseTestRefHeaderNoContentResponse parses an HTTP response from a TestRefHeaderNoContentWithResponse call
func ParseTestRefHeaderNoContentResponse(rsp *http.Response) (*TestRefHeaderNoContentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TestRefHeaderNoContentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /test-header-fixed-nocontent)
	TestHeaderFixedNoContent(w http.ResponseWriter, r *http.Request)

	// (GET /test-header-nocontent)
	TestHeaderNoContent(w http.ResponseWriter, r *http.Request)

	// (GET /test-ref-header-fixed-nocontent)
	TestRefHeaderFixedNoContent(w http.ResponseWriter, r *http.Request)

	// (GET /test-ref-header-nocontent)
	TestRefHeaderNoContent(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /test-header-fixed-nocontent)
func (_ Unimplemented) TestHeaderFixedNoContent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /test-header-nocontent)
func (_ Unimplemented) TestHeaderNoContent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /test-ref-header-fixed-nocontent)
func (_ Unimplemented) TestRefHeaderFixedNoContent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /test-ref-header-nocontent)
func (_ Unimplemented) TestRefHeaderNoContent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// TestHeaderFixedNoContent operation middleware
func (siw *ServerInterfaceWrapper) TestHeaderFixedNoContent(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestHeaderFixedNoContent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// TestHeaderNoContent operation middleware
func (siw *ServerInterfaceWrapper) TestHeaderNoContent(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestHeaderNoContent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// TestRefHeaderFixedNoContent operation middleware
func (siw *ServerInterfaceWrapper) TestRefHeaderFixedNoContent(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestRefHeaderFixedNoContent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// TestRefHeaderNoContent operation middleware
func (siw *ServerInterfaceWrapper) TestRefHeaderNoContent(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestRefHeaderNoContent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/test-header-fixed-nocontent", wrapper.TestHeaderFixedNoContent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/test-header-nocontent", wrapper.TestHeaderNoContent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/test-ref-header-fixed-nocontent", wrapper.TestRefHeaderFixedNoContent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/test-ref-header-nocontent", wrapper.TestRefHeaderNoContent)
	})

	return r
}

type TestRespRefHeaderFixedNoContentResponseHeaders struct {
	Header1 string
	Header2 int
}
type TestRespRefHeaderFixedNoContentResponse struct {
	Headers TestRespRefHeaderFixedNoContentResponseHeaders
}

type TestRespRefHeaderNoContentResponseHeaders struct {
	Header1 string
	Header2 int
}
type TestRespRefHeaderNoContentResponse struct {
	Headers TestRespRefHeaderNoContentResponseHeaders
}

type TestHeaderFixedNoContentRequestObject struct {
}

type TestHeaderFixedNoContentResponseObject interface {
	VisitTestHeaderFixedNoContentResponse(w http.ResponseWriter) error
}

type TestHeaderFixedNoContent204ResponseHeaders struct {
	Header1 string
	Header2 int
}

type TestHeaderFixedNoContent204Response struct {
	Headers TestHeaderFixedNoContent204ResponseHeaders
}

func (response TestHeaderFixedNoContent204Response) VisitTestHeaderFixedNoContentResponse(w http.ResponseWriter) error {
	w.Header().Set("header1", fmt.Sprint(response.Headers.Header1))
	w.Header().Set("header2", fmt.Sprint(response.Headers.Header2))
	w.WriteHeader(204)
	return nil
}

type TestHeaderNoContentRequestObject struct {
}

type TestHeaderNoContentResponseObject interface {
	VisitTestHeaderNoContentResponse(w http.ResponseWriter) error
}

type TestHeaderNoContentdefaultResponseHeaders struct {
	Header1 string
	Header2 int
}

type TestHeaderNoContentdefaultResponse struct {
	Headers TestHeaderNoContentdefaultResponseHeaders

	StatusCode int
}

func (response TestHeaderNoContentdefaultResponse) VisitTestHeaderNoContentResponse(w http.ResponseWriter) error {
	w.Header().Set("header1", fmt.Sprint(response.Headers.Header1))
	w.Header().Set("header2", fmt.Sprint(response.Headers.Header2))
	w.WriteHeader(response.StatusCode)
	return nil
}

type TestRefHeaderFixedNoContentRequestObject struct {
}

type TestRefHeaderFixedNoContentResponseObject interface {
	VisitTestRefHeaderFixedNoContentResponse(w http.ResponseWriter) error
}

type TestRefHeaderFixedNoContent204Response = TestRespRefHeaderFixedNoContentResponse

func (response TestRefHeaderFixedNoContent204Response) VisitTestRefHeaderFixedNoContentResponse(w http.ResponseWriter) error {
	w.Header().Set("header1", fmt.Sprint(response.Headers.Header1))
	w.Header().Set("header2", fmt.Sprint(response.Headers.Header2))
	w.WriteHeader(204)
	return nil
}

type TestRefHeaderNoContentRequestObject struct {
}

type TestRefHeaderNoContentResponseObject interface {
	VisitTestRefHeaderNoContentResponse(w http.ResponseWriter) error
}

type TestRefHeaderNoContentdefaultResponse struct {
	Headers TestRespRefHeaderNoContentResponseHeaders

	StatusCode int
}

func (response TestRefHeaderNoContentdefaultResponse) VisitTestRefHeaderNoContentResponse(w http.ResponseWriter) error {
	w.Header().Set("header1", fmt.Sprint(response.Headers.Header1))
	w.Header().Set("header2", fmt.Sprint(response.Headers.Header2))
	w.WriteHeader(response.StatusCode)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /test-header-fixed-nocontent)
	TestHeaderFixedNoContent(ctx context.Context, request TestHeaderFixedNoContentRequestObject) (TestHeaderFixedNoContentResponseObject, error)

	// (GET /test-header-nocontent)
	TestHeaderNoContent(ctx context.Context, request TestHeaderNoContentRequestObject) (TestHeaderNoContentResponseObject, error)

	// (GET /test-ref-header-fixed-nocontent)
	TestRefHeaderFixedNoContent(ctx context.Context, request TestRefHeaderFixedNoContentRequestObject) (TestRefHeaderFixedNoContentResponseObject, error)

	// (GET /test-ref-header-nocontent)
	TestRefHeaderNoContent(ctx context.Context, request TestRefHeaderNoContentRequestObject) (TestRefHeaderNoContentResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// TestHeaderFixedNoContent operation middleware
func (sh *strictHandler) TestHeaderFixedNoContent(w http.ResponseWriter, r *http.Request) {
	var request TestHeaderFixedNoContentRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TestHeaderFixedNoContent(ctx, request.(TestHeaderFixedNoContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TestHeaderFixedNoContent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TestHeaderFixedNoContentResponseObject); ok {
		if err := validResponse.VisitTestHeaderFixedNoContentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TestHeaderNoContent operation middleware
func (sh *strictHandler) TestHeaderNoContent(w http.ResponseWriter, r *http.Request) {
	var request TestHeaderNoContentRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TestHeaderNoContent(ctx, request.(TestHeaderNoContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TestHeaderNoContent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TestHeaderNoContentResponseObject); ok {
		if err := validResponse.VisitTestHeaderNoContentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TestRefHeaderFixedNoContent operation middleware
func (sh *strictHandler) TestRefHeaderFixedNoContent(w http.ResponseWriter, r *http.Request) {
	var request TestRefHeaderFixedNoContentRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TestRefHeaderFixedNoContent(ctx, request.(TestRefHeaderFixedNoContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TestRefHeaderFixedNoContent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TestRefHeaderFixedNoContentResponseObject); ok {
		if err := validResponse.VisitTestRefHeaderFixedNoContentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TestRefHeaderNoContent operation middleware
func (sh *strictHandler) TestRefHeaderNoContent(w http.ResponseWriter, r *http.Request) {
	var request TestRefHeaderNoContentRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TestRefHeaderNoContent(ctx, request.(TestRefHeaderNoContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TestRefHeaderNoContent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TestRefHeaderNoContentResponseObject); ok {
		if err := validResponse.VisitTestRefHeaderNoContentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
