// Package oldnullable provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package oldnullable

// Test defines model for Test.
type Test struct {
	NullableRequired *int `json:"NullableRequired"`
}
