// Package pkg1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package pkg1

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/labstack/echo/v4"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// TestFixedNoContent request
	TestFixedNoContent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TestNoContent request
	TestNoContent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TestRefFixedNoContent request
	TestRefFixedNoContent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TestRefNoContent request
	TestRefNoContent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) TestFixedNoContent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTestFixedNoContentRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TestNoContent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTestNoContentRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TestRefFixedNoContent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTestRefFixedNoContentRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TestRefNoContent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTestRefNoContentRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewTestFixedNoContentRequest generates requests for TestFixedNoContent
func NewTestFixedNoContentRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/test-fixed-nocontent")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTestNoContentRequest generates requests for TestNoContent
func NewTestNoContentRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/test-nocontent")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTestRefFixedNoContentRequest generates requests for TestRefFixedNoContent
func NewTestRefFixedNoContentRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/test-ref-fixed-nocontent")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTestRefNoContentRequest generates requests for TestRefNoContent
func NewTestRefNoContentRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/test-ref-nocontent")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// TestFixedNoContentWithResponse request
	TestFixedNoContentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestFixedNoContentResponse, error)

	// TestNoContentWithResponse request
	TestNoContentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestNoContentResponse, error)

	// TestRefFixedNoContentWithResponse request
	TestRefFixedNoContentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestRefFixedNoContentResponse, error)

	// TestRefNoContentWithResponse request
	TestRefNoContentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestRefNoContentResponse, error)
}

type TestFixedNoContentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r TestFixedNoContentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TestFixedNoContentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TestNoContentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r TestNoContentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TestNoContentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TestRefFixedNoContentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r TestRefFixedNoContentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TestRefFixedNoContentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TestRefNoContentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r TestRefNoContentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TestRefNoContentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// TestFixedNoContentWithResponse request returning *TestFixedNoContentResponse
func (c *ClientWithResponses) TestFixedNoContentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestFixedNoContentResponse, error) {
	rsp, err := c.TestFixedNoContent(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTestFixedNoContentResponse(rsp)
}

// TestNoContentWithResponse request returning *TestNoContentResponse
func (c *ClientWithResponses) TestNoContentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestNoContentResponse, error) {
	rsp, err := c.TestNoContent(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTestNoContentResponse(rsp)
}

// TestRefFixedNoContentWithResponse request returning *TestRefFixedNoContentResponse
func (c *ClientWithResponses) TestRefFixedNoContentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestRefFixedNoContentResponse, error) {
	rsp, err := c.TestRefFixedNoContent(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTestRefFixedNoContentResponse(rsp)
}

// TestRefNoContentWithResponse request returning *TestRefNoContentResponse
func (c *ClientWithResponses) TestRefNoContentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestRefNoContentResponse, error) {
	rsp, err := c.TestRefNoContent(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTestRefNoContentResponse(rsp)
}

// ParseTestFixedNoContentResponse parses an HTTP response from a TestFixedNoContentWithResponse call
func ParseTestFixedNoContentResponse(rsp *http.Response) (*TestFixedNoContentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TestFixedNoContentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseTestNoContentResponse parses an HTTP response from a TestNoContentWithResponse call
func ParseTestNoContentResponse(rsp *http.Response) (*TestNoContentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TestNoContentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseTestRefFixedNoContentResponse parses an HTTP response from a TestRefFixedNoContentWithResponse call
func ParseTestRefFixedNoContentResponse(rsp *http.Response) (*TestRefFixedNoContentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TestRefFixedNoContentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseTestRefNoContentResponse parses an HTTP response from a TestRefNoContentWithResponse call
func ParseTestRefNoContentResponse(rsp *http.Response) (*TestRefNoContentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TestRefNoContentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /test-fixed-nocontent)
	TestFixedNoContent(ctx echo.Context) error

	// (GET /test-nocontent)
	TestNoContent(ctx echo.Context) error

	// (GET /test-ref-fixed-nocontent)
	TestRefFixedNoContent(ctx echo.Context) error

	// (GET /test-ref-nocontent)
	TestRefNoContent(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// TestFixedNoContent converts echo context to params.
func (w *ServerInterfaceWrapper) TestFixedNoContent(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.TestFixedNoContent(ctx)
	return err
}

// TestNoContent converts echo context to params.
func (w *ServerInterfaceWrapper) TestNoContent(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.TestNoContent(ctx)
	return err
}

// TestRefFixedNoContent converts echo context to params.
func (w *ServerInterfaceWrapper) TestRefFixedNoContent(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.TestRefFixedNoContent(ctx)
	return err
}

// TestRefNoContent converts echo context to params.
func (w *ServerInterfaceWrapper) TestRefNoContent(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.TestRefNoContent(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/test-fixed-nocontent", wrapper.TestFixedNoContent)
	router.GET(baseURL+"/test-nocontent", wrapper.TestNoContent)
	router.GET(baseURL+"/test-ref-fixed-nocontent", wrapper.TestRefFixedNoContent)
	router.GET(baseURL+"/test-ref-nocontent", wrapper.TestRefNoContent)

}

type TestRespRefFixedNoContentResponse struct {
}

type TestRespRefNoContentResponse struct {
}

type TestFixedNoContentRequestObject struct {
}

type TestFixedNoContentResponseObject interface {
	VisitTestFixedNoContentResponse(w http.ResponseWriter) error
}

type TestFixedNoContent204Response struct {
}

func (response TestFixedNoContent204Response) VisitTestFixedNoContentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type TestNoContentRequestObject struct {
}

type TestNoContentResponseObject interface {
	VisitTestNoContentResponse(w http.ResponseWriter) error
}

type TestNoContentdefaultResponse struct {
	StatusCode int
}

func (response TestNoContentdefaultResponse) VisitTestNoContentResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

type TestRefFixedNoContentRequestObject struct {
}

type TestRefFixedNoContentResponseObject interface {
	VisitTestRefFixedNoContentResponse(w http.ResponseWriter) error
}

type TestRefFixedNoContent204Response = TestRespRefFixedNoContentResponse

func (response TestRefFixedNoContent204Response) VisitTestRefFixedNoContentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type TestRefNoContentRequestObject struct {
}

type TestRefNoContentResponseObject interface {
	VisitTestRefNoContentResponse(w http.ResponseWriter) error
}

type TestRefNoContentdefaultResponse struct {
	StatusCode int
}

func (response TestRefNoContentdefaultResponse) VisitTestRefNoContentResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /test-fixed-nocontent)
	TestFixedNoContent(ctx context.Context, request TestFixedNoContentRequestObject) (TestFixedNoContentResponseObject, error)

	// (GET /test-nocontent)
	TestNoContent(ctx context.Context, request TestNoContentRequestObject) (TestNoContentResponseObject, error)

	// (GET /test-ref-fixed-nocontent)
	TestRefFixedNoContent(ctx context.Context, request TestRefFixedNoContentRequestObject) (TestRefFixedNoContentResponseObject, error)

	// (GET /test-ref-nocontent)
	TestRefNoContent(ctx context.Context, request TestRefNoContentRequestObject) (TestRefNoContentResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// TestFixedNoContent operation middleware
func (sh *strictHandler) TestFixedNoContent(ctx echo.Context) error {
	var request TestFixedNoContentRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.TestFixedNoContent(ctx.Request().Context(), request.(TestFixedNoContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TestFixedNoContent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(TestFixedNoContentResponseObject); ok {
		return validResponse.VisitTestFixedNoContentResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// TestNoContent operation middleware
func (sh *strictHandler) TestNoContent(ctx echo.Context) error {
	var request TestNoContentRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.TestNoContent(ctx.Request().Context(), request.(TestNoContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TestNoContent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(TestNoContentResponseObject); ok {
		return validResponse.VisitTestNoContentResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// TestRefFixedNoContent operation middleware
func (sh *strictHandler) TestRefFixedNoContent(ctx echo.Context) error {
	var request TestRefFixedNoContentRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.TestRefFixedNoContent(ctx.Request().Context(), request.(TestRefFixedNoContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TestRefFixedNoContent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(TestRefFixedNoContentResponseObject); ok {
		return validResponse.VisitTestRefFixedNoContentResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// TestRefNoContent operation middleware
func (sh *strictHandler) TestRefNoContent(ctx echo.Context) error {
	var request TestRefNoContentRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.TestRefNoContent(ctx.Request().Context(), request.(TestRefNoContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TestRefNoContent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(TestRefNoContentResponseObject); ok {
		return validResponse.VisitTestRefNoContentResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
