// Code generated by generator/generate.go DO NOT EDIT.

package pkg1_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/stretchr/testify/assert"

	"github.com/deepmap/oapi-codegen/v2/internal/test/strict-server-matrix/pkg1"
)

type strictServerInterface struct{}

func (s strictServerInterface) TestText(ctx context.Context, request pkg1.TestTextRequestObject) (pkg1.TestTextResponseObject, error) {
	return pkg1.TestTextdefaultTextResponse{
		Body:       "bar",
		StatusCode: 200,
	}, nil
}

func TestText(t *testing.T) {
	hh := pkg1.Handler(pkg1.NewStrictHandler(strictServerInterface{}, nil))

	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !assert.Equal(t, "/test-text", r.URL.Path) {
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		hh.ServeHTTP(w, r)
	}))
	defer ts.Close()

	c, err := pkg1.NewClientWithResponses(ts.URL)
	assert.NoError(t, err)
	res, err := c.TestTextWithResponse(context.TODO())
	assert.NoError(t, err)
	assert.Equal(t, 200, res.StatusCode())
	assert.Equal(t, "text/plain", res.HTTPResponse.Header.Get("Content-Type"))
	assert.Equal(t, []byte("bar"), res.Body)
}

func (s strictServerInterface) TestHeaderText(ctx context.Context, request pkg1.TestHeaderTextRequestObject) (pkg1.TestHeaderTextResponseObject, error) {
	return pkg1.TestHeaderTextdefaultTextResponse{
		Body: "bar",
		Headers: pkg1.TestHeaderTextdefaultResponseHeaders{
			Header1: "foo",
			Header2: 123,
		},
		StatusCode: 200,
	}, nil
}

func TestHeaderText(t *testing.T) {
	hh := pkg1.Handler(pkg1.NewStrictHandler(strictServerInterface{}, nil))

	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !assert.Equal(t, "/test-header-text", r.URL.Path) {
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		hh.ServeHTTP(w, r)
	}))
	defer ts.Close()

	c, err := pkg1.NewClientWithResponses(ts.URL)
	assert.NoError(t, err)
	res, err := c.TestHeaderTextWithResponse(context.TODO())
	assert.NoError(t, err)
	assert.Equal(t, 200, res.StatusCode())
	assert.Equal(t, "foo", res.HTTPResponse.Header.Get("header1"))
	assert.Equal(t, "123", res.HTTPResponse.Header.Get("header2"))
	assert.Equal(t, "text/plain", res.HTTPResponse.Header.Get("Content-Type"))
	assert.Equal(t, []byte("bar"), res.Body)
}

func (s strictServerInterface) TestHeaderFixedText(ctx context.Context, request pkg1.TestHeaderFixedTextRequestObject) (pkg1.TestHeaderFixedTextResponseObject, error) {
	return pkg1.TestHeaderFixedText200TextResponse{
		Body: "bar",
		Headers: pkg1.TestHeaderFixedText200ResponseHeaders{
			Header1: "foo",
			Header2: 123,
		},
	}, nil
}

func TestHeaderFixedText(t *testing.T) {
	hh := pkg1.Handler(pkg1.NewStrictHandler(strictServerInterface{}, nil))

	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !assert.Equal(t, "/test-header-fixed-text", r.URL.Path) {
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		hh.ServeHTTP(w, r)
	}))
	defer ts.Close()

	c, err := pkg1.NewClientWithResponses(ts.URL)
	assert.NoError(t, err)
	res, err := c.TestHeaderFixedTextWithResponse(context.TODO())
	assert.NoError(t, err)
	assert.Equal(t, 200, res.StatusCode())
	assert.Equal(t, "foo", res.HTTPResponse.Header.Get("header1"))
	assert.Equal(t, "123", res.HTTPResponse.Header.Get("header2"))
	assert.Equal(t, "text/plain", res.HTTPResponse.Header.Get("Content-Type"))
	assert.Equal(t, []byte("bar"), res.Body)
}
