// Package pkg1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package pkg1

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// TestSchema defines model for TestSchema.
type TestSchema struct {
	Field1 string `json:"field1"`
	Field2 int    `json:"field2"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// TestRefFixedFormdata request
	TestRefFixedFormdata(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TestRefFormdata request
	TestRefFormdata(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TestRefHeaderFixedFormdata request
	TestRefHeaderFixedFormdata(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TestRefHeaderFormdata request
	TestRefHeaderFormdata(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) TestRefFixedFormdata(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTestRefFixedFormdataRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TestRefFormdata(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTestRefFormdataRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TestRefHeaderFixedFormdata(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTestRefHeaderFixedFormdataRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TestRefHeaderFormdata(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTestRefHeaderFormdataRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewTestRefFixedFormdataRequest generates requests for TestRefFixedFormdata
func NewTestRefFixedFormdataRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/test-ref-fixed-formdata")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTestRefFormdataRequest generates requests for TestRefFormdata
func NewTestRefFormdataRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/test-ref-formdata")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTestRefHeaderFixedFormdataRequest generates requests for TestRefHeaderFixedFormdata
func NewTestRefHeaderFixedFormdataRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/test-ref-header-fixed-formdata")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTestRefHeaderFormdataRequest generates requests for TestRefHeaderFormdata
func NewTestRefHeaderFormdataRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/test-ref-header-formdata")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// TestRefFixedFormdataWithResponse request
	TestRefFixedFormdataWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestRefFixedFormdataResponse, error)

	// TestRefFormdataWithResponse request
	TestRefFormdataWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestRefFormdataResponse, error)

	// TestRefHeaderFixedFormdataWithResponse request
	TestRefHeaderFixedFormdataWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestRefHeaderFixedFormdataResponse, error)

	// TestRefHeaderFormdataWithResponse request
	TestRefHeaderFormdataWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestRefHeaderFormdataResponse, error)
}

type TestRefFixedFormdataResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r TestRefFixedFormdataResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TestRefFixedFormdataResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TestRefFormdataResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r TestRefFormdataResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TestRefFormdataResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TestRefHeaderFixedFormdataResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r TestRefHeaderFixedFormdataResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TestRefHeaderFixedFormdataResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TestRefHeaderFormdataResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r TestRefHeaderFormdataResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TestRefHeaderFormdataResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// TestRefFixedFormdataWithResponse request returning *TestRefFixedFormdataResponse
func (c *ClientWithResponses) TestRefFixedFormdataWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestRefFixedFormdataResponse, error) {
	rsp, err := c.TestRefFixedFormdata(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTestRefFixedFormdataResponse(rsp)
}

// TestRefFormdataWithResponse request returning *TestRefFormdataResponse
func (c *ClientWithResponses) TestRefFormdataWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestRefFormdataResponse, error) {
	rsp, err := c.TestRefFormdata(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTestRefFormdataResponse(rsp)
}

// TestRefHeaderFixedFormdataWithResponse request returning *TestRefHeaderFixedFormdataResponse
func (c *ClientWithResponses) TestRefHeaderFixedFormdataWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestRefHeaderFixedFormdataResponse, error) {
	rsp, err := c.TestRefHeaderFixedFormdata(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTestRefHeaderFixedFormdataResponse(rsp)
}

// TestRefHeaderFormdataWithResponse request returning *TestRefHeaderFormdataResponse
func (c *ClientWithResponses) TestRefHeaderFormdataWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TestRefHeaderFormdataResponse, error) {
	rsp, err := c.TestRefHeaderFormdata(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTestRefHeaderFormdataResponse(rsp)
}

// ParseTestRefFixedFormdataResponse parses an HTTP response from a TestRefFixedFormdataWithResponse call
func ParseTestRefFixedFormdataResponse(rsp *http.Response) (*TestRefFixedFormdataResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TestRefFixedFormdataResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseTestRefFormdataResponse parses an HTTP response from a TestRefFormdataWithResponse call
func ParseTestRefFormdataResponse(rsp *http.Response) (*TestRefFormdataResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TestRefFormdataResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseTestRefHeaderFixedFormdataResponse parses an HTTP response from a TestRefHeaderFixedFormdataWithResponse call
func ParseTestRefHeaderFixedFormdataResponse(rsp *http.Response) (*TestRefHeaderFixedFormdataResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TestRefHeaderFixedFormdataResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseTestRefHeaderFormdataResponse parses an HTTP response from a TestRefHeaderFormdataWithResponse call
func ParseTestRefHeaderFormdataResponse(rsp *http.Response) (*TestRefHeaderFormdataResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TestRefHeaderFormdataResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /test-ref-fixed-formdata)
	TestRefFixedFormdata(w http.ResponseWriter, r *http.Request)

	// (GET /test-ref-formdata)
	TestRefFormdata(w http.ResponseWriter, r *http.Request)

	// (GET /test-ref-header-fixed-formdata)
	TestRefHeaderFixedFormdata(w http.ResponseWriter, r *http.Request)

	// (GET /test-ref-header-formdata)
	TestRefHeaderFormdata(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /test-ref-fixed-formdata)
func (_ Unimplemented) TestRefFixedFormdata(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /test-ref-formdata)
func (_ Unimplemented) TestRefFormdata(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /test-ref-header-fixed-formdata)
func (_ Unimplemented) TestRefHeaderFixedFormdata(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /test-ref-header-formdata)
func (_ Unimplemented) TestRefHeaderFormdata(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// TestRefFixedFormdata operation middleware
func (siw *ServerInterfaceWrapper) TestRefFixedFormdata(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestRefFixedFormdata(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// TestRefFormdata operation middleware
func (siw *ServerInterfaceWrapper) TestRefFormdata(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestRefFormdata(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// TestRefHeaderFixedFormdata operation middleware
func (siw *ServerInterfaceWrapper) TestRefHeaderFixedFormdata(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestRefHeaderFixedFormdata(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// TestRefHeaderFormdata operation middleware
func (siw *ServerInterfaceWrapper) TestRefHeaderFormdata(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestRefHeaderFormdata(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/test-ref-fixed-formdata", wrapper.TestRefFixedFormdata)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/test-ref-formdata", wrapper.TestRefFormdata)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/test-ref-header-fixed-formdata", wrapper.TestRefHeaderFixedFormdata)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/test-ref-header-formdata", wrapper.TestRefHeaderFormdata)
	})

	return r
}

type TestRespRefFixedFormdataFormdataResponse TestSchema

type TestRespRefFormdataFormdataResponse TestSchema

type TestRespRefHeaderFixedFormdataResponseHeaders struct {
	Header1 string
	Header2 int
}
type TestRespRefHeaderFixedFormdataFormdataResponse struct {
	Body TestSchema

	Headers TestRespRefHeaderFixedFormdataResponseHeaders
}

type TestRespRefHeaderFormdataResponseHeaders struct {
	Header1 string
	Header2 int
}
type TestRespRefHeaderFormdataFormdataResponse struct {
	Body TestSchema

	Headers TestRespRefHeaderFormdataResponseHeaders
}

type TestRefFixedFormdataRequestObject struct {
}

type TestRefFixedFormdataResponseObject interface {
	VisitTestRefFixedFormdataResponse(w http.ResponseWriter) error
}

type TestRefFixedFormdata200FormdataResponse struct {
	TestRespRefFixedFormdataFormdataResponse
}

func (response TestRefFixedFormdata200FormdataResponse) VisitTestRefFixedFormdataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/x-www-form-urlencoded")
	w.WriteHeader(200)

	if form, err := runtime.MarshalForm(response, nil); err != nil {
		return err
	} else {
		_, err := w.Write([]byte(form.Encode()))
		return err
	}
}

type TestRefFormdataRequestObject struct {
}

type TestRefFormdataResponseObject interface {
	VisitTestRefFormdataResponse(w http.ResponseWriter) error
}

type TestRefFormdatadefaultFormdataResponse struct {
	Body       TestSchema
	StatusCode int
}

func (response TestRefFormdatadefaultFormdataResponse) VisitTestRefFormdataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/x-www-form-urlencoded")
	w.WriteHeader(response.StatusCode)

	if form, err := runtime.MarshalForm(response.Body, nil); err != nil {
		return err
	} else {
		_, err := w.Write([]byte(form.Encode()))
		return err
	}
}

type TestRefHeaderFixedFormdataRequestObject struct {
}

type TestRefHeaderFixedFormdataResponseObject interface {
	VisitTestRefHeaderFixedFormdataResponse(w http.ResponseWriter) error
}

type TestRefHeaderFixedFormdata200FormdataResponse struct {
	TestRespRefHeaderFixedFormdataFormdataResponse
}

func (response TestRefHeaderFixedFormdata200FormdataResponse) VisitTestRefHeaderFixedFormdataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/x-www-form-urlencoded")
	w.Header().Set("header1", fmt.Sprint(response.Headers.Header1))
	w.Header().Set("header2", fmt.Sprint(response.Headers.Header2))
	w.WriteHeader(200)

	if form, err := runtime.MarshalForm(response.Body, nil); err != nil {
		return err
	} else {
		_, err := w.Write([]byte(form.Encode()))
		return err
	}
}

type TestRefHeaderFormdataRequestObject struct {
}

type TestRefHeaderFormdataResponseObject interface {
	VisitTestRefHeaderFormdataResponse(w http.ResponseWriter) error
}

type TestRefHeaderFormdatadefaultFormdataResponse struct {
	Body       TestSchema
	Headers    TestRespRefHeaderFormdataResponseHeaders
	StatusCode int
}

func (response TestRefHeaderFormdatadefaultFormdataResponse) VisitTestRefHeaderFormdataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/x-www-form-urlencoded")
	w.Header().Set("header1", fmt.Sprint(response.Headers.Header1))
	w.Header().Set("header2", fmt.Sprint(response.Headers.Header2))
	w.WriteHeader(response.StatusCode)

	if form, err := runtime.MarshalForm(response.Body, nil); err != nil {
		return err
	} else {
		_, err := w.Write([]byte(form.Encode()))
		return err
	}
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /test-ref-fixed-formdata)
	TestRefFixedFormdata(ctx context.Context, request TestRefFixedFormdataRequestObject) (TestRefFixedFormdataResponseObject, error)

	// (GET /test-ref-formdata)
	TestRefFormdata(ctx context.Context, request TestRefFormdataRequestObject) (TestRefFormdataResponseObject, error)

	// (GET /test-ref-header-fixed-formdata)
	TestRefHeaderFixedFormdata(ctx context.Context, request TestRefHeaderFixedFormdataRequestObject) (TestRefHeaderFixedFormdataResponseObject, error)

	// (GET /test-ref-header-formdata)
	TestRefHeaderFormdata(ctx context.Context, request TestRefHeaderFormdataRequestObject) (TestRefHeaderFormdataResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// TestRefFixedFormdata operation middleware
func (sh *strictHandler) TestRefFixedFormdata(w http.ResponseWriter, r *http.Request) {
	var request TestRefFixedFormdataRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TestRefFixedFormdata(ctx, request.(TestRefFixedFormdataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TestRefFixedFormdata")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TestRefFixedFormdataResponseObject); ok {
		if err := validResponse.VisitTestRefFixedFormdataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TestRefFormdata operation middleware
func (sh *strictHandler) TestRefFormdata(w http.ResponseWriter, r *http.Request) {
	var request TestRefFormdataRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TestRefFormdata(ctx, request.(TestRefFormdataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TestRefFormdata")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TestRefFormdataResponseObject); ok {
		if err := validResponse.VisitTestRefFormdataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TestRefHeaderFixedFormdata operation middleware
func (sh *strictHandler) TestRefHeaderFixedFormdata(w http.ResponseWriter, r *http.Request) {
	var request TestRefHeaderFixedFormdataRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TestRefHeaderFixedFormdata(ctx, request.(TestRefHeaderFixedFormdataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TestRefHeaderFixedFormdata")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TestRefHeaderFixedFormdataResponseObject); ok {
		if err := validResponse.VisitTestRefHeaderFixedFormdataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TestRefHeaderFormdata operation middleware
func (sh *strictHandler) TestRefHeaderFormdata(w http.ResponseWriter, r *http.Request) {
	var request TestRefHeaderFormdataRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TestRefHeaderFormdata(ctx, request.(TestRefHeaderFormdataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TestRefHeaderFormdata")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TestRefHeaderFormdataResponseObject); ok {
		if err := validResponse.VisitTestRefHeaderFormdataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
