// Package newnullable provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package newnullable

import "github.com/oapi-codegen/nullable"

// Test defines model for Test.
type Test struct {
	NullableRequired nullable.Nullable[int] `json:"NullableRequired"`
}
